version: '3'
services:
  mage:
    image: mageai/mageai:latest
    container_name: data-warehouse
    
    command: mage start data-warehouse
    environment:
      ENV: dev
      POSTGRES_DB: taxis
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: postgres
      PG_HOST_PORT: 5432
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src/
    restart: on-failure:5

  postgres:
    image: postgres:14
    restart: on-failure
    container_name: postgres-magic
    build:
      context: ./db
    environment:
      POSTGRES_DB: taxis
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"